version: "3.9"

services:
  redis:
    image: redis:7
    volumes:
      - redis-data:/data

  vote:
    build: ./vote
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis-data:
