name: CI - Docker Compose Voting App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build images using Docker Compose
      - name: Build images
        run: docker compose build

      # Run containers in background
      - name: Start services
        run: docker compose up -d

      # Give containers time to start
      - name: Wait for services
        run: sleep 10

      # Test Vote service
      - name: Test Vote service
        run: curl --fail http://localhost:5000 || (docker compose logs && exit 1)

      # Test Result service
      - name: Test Result service
        run: curl --fail http://localhost:5001 || (docker compose logs && exit 1)

      # Tear down
      - name: Stop services
        run: docker compose down -v

